url: "https://basspistol.com" # the base hostname & protocol for your site
permalink: /:categories/:year/:month/:day/:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "*.*~", "color_chart.txt", Gemfile, Gemfile.lock]
highlighter: pygments

title : 'Basspistol'
tagline: 'The Outernational Music Syndicate. Established in 2010'
timezone: Europe/Stockholm
banner: '/assets/img/basspistol_est_2010_square_bluegreen.jpg'
mblabel: '0f83baf3-4f44-44db-9e30-d5c05d7b77b9'

social_ids: [insta, twitter, facebook, soundcloud, tumblr, archive, mastodon]
social:
  insta: 'https://www.instagram.com/basspistol'
  twitter: 'https://twitter.com/bpist'
  facebook: 'https://www.facebook.com/basspistolQC'
  soundcloud: 'https://soundcloud.com/basspistol'
  tumblr: 'https://basspistol.tumblr.com'
  archive: 'https://archive.org/details/basspistol'
  mastodon: 'https://mastodon.art/@basspistol'

production_url : https://basspistol.com
baseurl : ''
shop_url: https://shop.basspistol.com/

# excerpt_separator: '<!--more-->'
pagination:
  enabled: true

collections:
  albums:
    output: true
    permalink: /albums/:name/
  tracks:
    output: true
  staff_members:
    _hide_content: 
      
plugins: 
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-last-modified-at
  
# defaults

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      _options:
        image:
          width: 960
          height: 430
          uploads_dir: "assets/img"
          resize_style: "cover"
          